import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, Compass, Leaf, MapPin } from "lucide-react";
import { destinations, tours } from "@/content/site";

export default function Home() { const featured = tours.filter(({ featured }) => featured); return <>
  <section className="hero"><Image src="/images/gorilla-trekking-volcanoes.png" alt="Travellers observing a mountain gorilla in Volcanoes National Park" fill priority sizes="100vw"/><div className="hero-shade"/><div className="hero-content"><p className="kicker light">Born in Rwanda · Crafted for you</p><h1>Travel deeper.<br/><em>Feel East Africa.</em></h1><p className="hero-copy">Private journeys through wild landscapes, living cultures and rare encounters—designed by people who call this region home.</p><div className="actions"><Link className="button cream" href="/plan">Design my journey <ArrowUpRight/></Link><Link className="text-link light" href="/tours">Explore our safaris →</Link></div></div><a className="scroll" href="#intro"><ArrowDown/> Scroll to discover</a><div className="hero-stamp"><span>LOCAL<br/>EXPERTS</span><b>EA</b><span>PRIVATE<br/>JOURNEYS</span></div></section>
  <section id="intro" className="intro section"><div><p className="kicker">Welcome to our home</p><h2>Close on the map.<br/><em>Infinite in feeling.</em></h2></div><div className="intro-copy"><p>Mountain mist, open savannah, living culture and the rare privilege of meeting great apes in their forest home.</p><p>We create journeys through Rwanda and East Africa personally, responsibly and at your pace.</p><Link className="text-link" href="/about">Meet Bru-Safaris →</Link></div></section>
  <section className="journeys section"><div className="section-head"><div><p className="kicker">Journeys worth taking</p><h2>Signature <em>safaris</em></h2></div><Link className="text-link" href="/tours">View all nine journeys →</Link></div><div className="tour-grid">{featured.map((item, index) => <Link className="tour-card" href={`/tours/${item.slug}`} key={item.slug}><div className="card-image"><Image src={item.image} alt={item.title} fill sizes="(max-width: 800px) 100vw, 33vw"/><span>{String(index + 1).padStart(2, "0")}</span></div><div className="card-copy"><p>{item.region} · {item.duration}</p><h3>{item.title}</h3><span className="arrow">↗</span></div></Link>)}</div></section>
  <section className="why section"><div className="why-image"><Image src="/images/rwanda-green-highlands.png" alt="Rwanda's green terraced highlands" fill sizes="(max-width: 800px) 100vw, 50vw"/></div><div className="why-copy"><p className="kicker light">Why travel with us</p><h2>Not just a trip.<br/><em>A connection.</em></h2>{[[Compass, "Designed around you", "Every journey begins with your interests, energy, priorities and preferred level of comfort."], [MapPin, "Rooted in Kigali", "Our local perspective creates coherent routes and experiences beyond the obvious."], [Leaf, "Travel with care", "We favour locally rooted partners and experiences that respect communities and landscapes."]].map(([Icon, title, text]) => <div className="reason" key={String(title)}><Icon/><div><h3>{String(title)}</h3><p>{String(text)}</p></div></div>)}</div></section>
  <section className="destinations section"><div className="section-head"><div><p className="kicker">Start with Rwanda</p><h2>Wildly <em>different.</em><br/>Wonderfully close.</h2></div></div><div className="destination-row">{destinations.map((destination) => <Link href={`/destinations/${destination.slug}`} className="destination-card" key={destination.slug}><Image src={destination.image} fill alt={destination.name} sizes="(max-width: 800px) 100vw, 33vw"/><div><span>{destination.eyebrow}</span><h3>{destination.name}</h3><p>{destination.text}</p></div></Link>)}</div></section>
  <section className="planner-cta"><Image src="/images/lake-kivu-sunset.png" fill alt="Golden sunset over Lake Kivu" sizes="100vw"/><div className="hero-shade"/><div><p className="kicker light">Made for you, from the ground up</p><h2>Your journey.<br/><em>Your rhythm.</em></h2><p>Tell us what moves you. We’ll shape a private East Africa experience around it.</p><Link href="/plan" className="button cream">Start planning <ArrowUpRight/></Link></div></section>
</>; }
