export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  readTime: string;
  image: string;
  published: string;
  sections: { heading: string; body: string }[];
};

export const posts: BlogPost[] = [
  { slug: "best-time-gorilla-trekking-rwanda", title: "The best time for gorilla trekking in Rwanda", excerpt: "How seasons, trail conditions and permit planning shape a Volcanoes National Park journey.", category: "Gorilla trekking", readTime: "6 min read", image: "/images/gorilla-trekking-volcanoes.png", published: "2026-07-10", sections: [{ heading: "A year-round experience", body: "Mountain gorilla trekking operates throughout the year. The drier periods from June to September and December to February can make trails more manageable, while greener months bring lush photography and fewer visitors." }, { heading: "Plan permits first", body: "Permit availability should anchor your travel dates. Build flexibility into the wider itinerary and confirm current requirements with your safari designer before booking flights." }] },
  { slug: "luxury-mid-range-standard-safari", title: "Luxury, mid-range or standard: choosing your safari style", excerpt: "A practical guide to accommodation levels without reducing the decision to room price alone.", category: "Planning", readTime: "7 min read", image: "/images/kigali-hospitality.png", published: "2026-07-08", sections: [{ heading: "Location matters", body: "A well-positioned lodge can reduce driving and create better wildlife hours. We assess access, service, atmosphere and routing—not only room category." }, { heading: "Mixing levels", body: "Many thoughtful itineraries combine an exceptional lodge at a highlight destination with simpler stays elsewhere. Your designer can make those trade-offs explicit." }] },
  { slug: "rwanda-uganda-combination-safari", title: "How to combine Rwanda and Uganda well", excerpt: "Border logistics, pacing and the experiences that make a two-country journey worthwhile.", category: "Routes", readTime: "8 min read", image: "/images/rwanda-green-highlands.png", published: "2026-07-05", sections: [{ heading: "Choose a natural route", body: "Volcanoes, Bwindi and Lake Bunyonyi connect naturally. Longer journeys can continue to Queen Elizabeth and Kibale without unnecessary backtracking." }, { heading: "Leave room to breathe", body: "Border crossings and mountain roads reward realistic timings. Two-night stays and occasional slower mornings keep the journey restorative." }] },
  { slug: "what-to-pack-rwanda-safari", title: "What to pack for a Rwanda safari", excerpt: "A concise packing system for forest treks, game drives, city time and changing elevations.", category: "Practical guide", readTime: "5 min read", image: "/images/nyungwe-canopy-walk.png", published: "2026-07-02", sections: [{ heading: "Forest essentials", body: "Bring broken-in waterproof footwear, long trousers, gardening gloves, rain protection and a small daypack. Neutral layers work across cool mornings and warmer afternoons." }, { heading: "Travel light", body: "Soft-sided luggage is easier in safari vehicles and light aircraft. Keep medication, documents and one change of clothes in your hand luggage." }] },
  { slug: "responsible-gorilla-trekking", title: "A respectful approach to gorilla trekking", excerpt: "Why health rules, guide instructions and thoughtful behaviour protect both wildlife and guests.", category: "Conservation", readTime: "6 min read", image: "/images/mountain-gorilla-family.png", published: "2026-06-28", sections: [{ heading: "Follow the briefing", body: "Distance, group size, viewing time and health rules are conservation tools. Always follow ranger instructions and never trek when unwell." }, { heading: "Look beyond the photograph", body: "Quiet observation makes the encounter richer. Avoid sudden movement, keep voices low and let the forest set the pace." }] },
  { slug: "first-east-africa-safari-planning", title: "Planning your first East Africa safari", excerpt: "The key decisions that turn a long wish list into a coherent, rewarding private journey.", category: "Planning", readTime: "9 min read", image: "/images/akagera-zebras.png", published: "2026-06-24", sections: [{ heading: "Start with priorities", body: "Choose two or three non-negotiable experiences, then let geography determine the route. Trying to include every park often creates a rushed trip." }, { heading: "Design around energy", body: "Early wildlife starts and forest treks are rewarding but demanding. Alternate active days with scenic transfers or relaxed lodge time." }] },
];
