"use client";
import { FormEvent, useState } from "react";

const interests = ["Mountain gorillas", "Chimpanzees", "Golden monkeys", "Classic wildlife", "Birding", "Culture and history", "Photography", "Hiking", "Lake time", "Food"];
export function EnquiryForm({ trip = "Custom East Africa safari" }: { trip?: string }) {
  const [state, setState] = useState<"idle" | "sending" | "success" | "error">("idle");
  const [reference, setReference] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setState("sending"); const form = new FormData(event.currentTarget);
    const payload = { ...Object.fromEntries(form), countries: form.getAll("countries"), interests: form.getAll("interests"), consent: form.get("consent") === "on", adults: Number(form.get("adults")), children: Number(form.get("children")) };
    try { const response = await fetch("/api/enquiries", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(); setReference(data.reference); setState("success"); }
    catch { setState("error"); }
  }
  if (state === "success") return <div className="success" role="status"><span>✓</span><h3>Your journey has begun.</h3><p>Our Kigali team will review your ideas and reply personally. Reference: <b>{reference}</b></p></div>;
  return <form className="enquiry-form" onSubmit={submit}>
    <fieldset><legend>About you</legend><div className="field-grid"><label>Your name<input name="name" autoComplete="name" required minLength={2}/></label><label>Email address<input name="email" type="email" autoComplete="email" required/></label><label>Phone / WhatsApp<input name="phone" type="tel" autoComplete="tel"/></label><label>Journey interest<input name="trip" defaultValue={trip} required/></label></div></fieldset>
    <fieldset><legend>Your journey</legend><div className="choice-group"><span>Countries</span>{["Rwanda", "Uganda", "Tanzania"].map((country) => <label className="check" key={country}><input type="checkbox" name="countries" value={country} defaultChecked={country === "Rwanda"}/>{country}</label>)}</div><div className="field-grid"><label>When would you like to travel?<input name="dates" placeholder="Month, year or flexible"/></label><label>Preferred duration<select name="duration" defaultValue="10–14 days"><option>8–10 days</option><option>10–14 days</option><option>15–18 days</option><option>19–21 days</option><option>Flexible</option></select></label><label>Adults<input name="adults" type="number" min="1" max="30" defaultValue="2" required/></label><label>Children<input name="children" type="number" min="0" max="20" defaultValue="0" required/></label><label>Accommodation level<select name="accommodation" defaultValue="Unsure"><option>Luxury</option><option>Mid-range</option><option>Standard</option><option>Mix levels</option><option>Unsure</option></select></label><label>Planning priority<select name="priorities" defaultValue="Balanced experience"><option>Exceptional stays</option><option>Balanced experience</option><option>Maximize value</option><option>Help me decide</option></select></label></div></fieldset>
    <fieldset><legend>What matters to you?</legend><div className="choice-grid">{interests.map((interest) => <label className="check" key={interest}><input type="checkbox" name="interests" value={interest} defaultChecked={interest === "Mountain gorillas"}/>{interest}</label>)}</div><label>Mobility or accessibility needs<textarea name="mobility" rows={3} placeholder="Share anything that will help us plan comfortable days."/></label><label>Dietary needs<textarea name="dietary" rows={3} placeholder="Allergies, preferences or religious requirements."/></label><label>Tell us what would make this trip special<textarea name="message" required minLength={10} rows={5} placeholder="Your ideal pace, celebrations, must-see experiences and anything else we should know."/></label></fieldset>
    <label className="check consent"><input type="checkbox" name="consent" required/>I agree that Bru-Safaris may use these details only to respond to and plan my enquiry.</label><input className="honeypot" name="website" tabIndex={-1} autoComplete="off"/><button className="button" disabled={state === "sending"}>{state === "sending" ? "Sending…" : "Request my itinerary →"}</button>{state === "error" && <p className="error" role="alert">We couldn’t send that. Check the required fields and try again.</p>}
  </form>;
}
