import type { Metadata } from "next";
import { site } from "@/content/site";

export const metadata: Metadata = { title: "Booking Terms, Cancellations & Guest Safety", description: "Bru Safaris booking, payment, cancellation, insurance, liability and emergency-response terms.", alternates: { canonical: "/terms" } };
const cancellationRows = [
  ["60 or more days", "75% refund", "25% cancellation fee"],
  ["51–59 days", "75% refund", "60+ day tier applied until a revised schedule is issued"],
  ["30–50 days", "50% refund", "50% cancellation fee"],
  ["15–29 days", "25% refund", "75% cancellation fee"],
  ["0–14 days or no-show", "No refund", "100% cancellation fee"],
];

export default function Terms() { return <article className="legal-page"><header><p className="kicker">Legal & operational</p><h1>Booking terms<br/><em>& guest safety.</em></h1><p>Effective 21 July 2026. These terms apply to bookings made directly with Bru Safaris and should be read with the final written itinerary and invoice.</p></header><div className="legal-body">
  <section><p className="kicker">01 · Booking and payment</p><h2>Confirming your journey</h2><h3>Deposit</h3><p>A 50% deposit of the total safari cost is required to confirm reservations. The deposit is non-refundable except where the cancellation schedule below expressly provides a refund.</p><h3>Permit fees</h3><p>Gorilla and chimpanzee permits must be paid in full when reserved. Rwanda gorilla permits currently cost US$1,500 per person per trekking day. Chimpanzee permit fees and all permit conditions will be reconfirmed in writing against the official booking platform before payment.</p><p>Permit allocations are normally non-refundable once issued. Any exception depends entirely on reimbursement by the responsible park authority.</p><h3>Balance</h3><p>The remaining balance is due 30 days before departure. A booking made within 30 days of departure requires immediate payment in full.</p><h3>Payment methods</h3><p>Payment may be made by direct bank transfer using the SWIFT details shown on the official invoice, or by credit/debit card. Any card-processing surcharge will be disclosed before payment.</p></section>
  <section><p className="kicker">02 · Cancellation and refunds</p><h2>If plans change</h2><p>Cancellations must be submitted in writing to <a href={`mailto:${site.email}`}>{site.email}</a>. Percentages apply to the total trip value excluding permit costs. A refund cannot exceed the amount Bru Safaris has received, and documented non-recoverable supplier costs may also be deducted where disclosed.</p><div className="policy-table" role="table" aria-label="Cancellation schedule"><div className="policy-row policy-head" role="row"><b>Notice before departure</b><b>Refund</b><b>Charge or application</b></div>{cancellationRows.map(([notice, refund, charge]) => <div className="policy-row" role="row" key={notice}><span>{notice}</span><span>{refund}</span><span>{charge}</span></div>)}</div><p>Approved refunds are returned through the original payment method where practicable. Bank, card and currency-conversion charges imposed by third parties are not refundable.</p></section>
  <section><p className="kicker">03 · Insurance and fitness</p><h2>Mandatory travel protection</h2><p>Every guest must hold comprehensive international travel insurance covering emergency medical treatment, medical evacuation, trip cancellation or interruption, and loss of personal belongings. Proof may be required before trekking or remote safari activities begin.</p><p>Guests must disclose relevant mobility, health or dietary needs during planning and follow medical advice about fitness for the booked activities.</p></section>
  <section><p className="kicker">04 · Risk and responsibility</p><h2>Wild places require care</h2><p>Wildlife safaris, primate trekking, hiking, mountaineering and rough-terrain travel carry inherent risks. Guests agree to follow guide, ranger and emergency instructions and to act responsibly around wildlife.</p><p>Bru Safaris coordinates services delivered by park authorities, lodges, transport providers and other suppliers. It is not responsible for events genuinely outside its reasonable control, including severe weather, road closures, park closures, public-health measures or civil disruption.</p><p>Nothing in these terms excludes or limits any responsibility, duty or consumer right that cannot lawfully be excluded under applicable Rwandan law. Bru Safaris remains responsible for its own acts and omissions and those of its employees or agents to the extent required by law.</p></section>
  <section><p className="kicker">05 · Field emergency procedure</p><h2>Response sequence</h2><ol className="response-steps"><li><b>Immediate assessment and first aid.</b><span>The driver-guide secures the area, stops the activity and provides first aid within the limits of their training and available equipment.</span></li><li><b>Activate emergency response.</b><span>The guide contacts Bru Safaris management on <a href={`tel:${site.phone}`}>{site.phone}</a>, park rangers and the appropriate public or private emergency service.</span></li><li><b>Evacuation and transfer.</b><span>Responders select the safest available ground or air evacuation option and the appropriate medical facility based on location, condition, weather and access.</span></li><li><b>Notify stakeholders.</b><span>After immediate care is underway, management contacts the guest’s insurer, nominated emergency contact and relevant consular authority when required.</span></li></ol><p>Response and transfer times cannot be guaranteed because terrain, weather, communications and provider availability vary.</p></section>
  <section><p className="kicker">06 · Gorilla encounter conduct</p><h2>Protecting guests and wildlife</h2><p>Guests must attend the official ranger briefing and follow ranger instructions throughout the trek. Bru Safaris requires guests to maintain at least seven metres from gorillas whenever conditions allow, avoid flash photography, keep voices low, avoid sudden movement and never trek when unwell.</p><p>Rwanda gorilla encounters are limited to a strict maximum of one hour, and the minimum trekking age is 15. Current permit and visitor rules should always be checked before travel.</p><a className="text-link" href="https://visitrwanda.com/interests/gorilla-tracking/">Read official Visit Rwanda guidance →</a></section>
  <aside><p className="kicker">Questions about these terms?</p><h2>Ask before you pay.</h2><p>Email <a href={`mailto:${site.email}`}>{site.email}</a> or call <a href={`tel:${site.phone}`}>{site.phone}</a>. The final written itinerary and invoice should identify any supplier-specific condition that differs from these general terms.</p></aside>
</div></article>; }
